# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2

references:
  container-defaults:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.1
  machine-defaults: &environment-defaults
    machine: true
  install-docker-compose: &install-docker-compose
    run:
      name: Install Docker Compose
      command: |
        sudo curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
  restore-cache: &restore-cache
    # Download and cache dependencies
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "tox.ini" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
  install-python3: &install-python3
    run:
      name: Install Python 3.6.1
      command: |
        curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
        pyenv install 3.6.1
  install-tox: &install-tox
    run:
      name: Install Tox
      command: sudo pip install tox
  fetch-dependencies-via-tox: &fetch-dependencies-via-tox
    run:
      name: Fetch dependencies via Tox environment
      command: tox -e phial --notest
  save-cache: &save-cache
    save_cache:
      paths:
       - ./tox
      key: v1-dependencies-{{ checksum "tox.ini" }}
  phial: &phial
    run:
      name: Run integration tests using Phial
      command: tox -e phial -- -m $GROUP

  steps: &steps
    steps:
      - checkout
      - *install-docker-compose
      - *restore-cache
      - *install-python3
      - *install-tox
      - *fetch-dependencies-via-tox
      - *save-cache
      - *phial


workflows:
  version: 2
  integration-tests:
    jobs:
      - centos-6
      - centos-7
      - oraclelinux-6
      - oraclelinux-7
      - debian-8
      - debian-9
      - ubuntu-1404
      - ubuntu-1604

jobs:
  centos-6:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: centos6

  centos-7:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: centos7
  oraclelinux-6:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: oraclelinux6
  oraclelinux-7:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: oraclelinux7
  ubuntu-1404:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: ubuntu1404
  ubuntu-1604:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: ubuntu1604
  debian-8:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: debian8
  debian-9:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: debian9
