# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2

references:
  machine-defaults: &environment-defaults
    machine: true
  install-docker-compose: &install-docker-compose
    run:
      name: Install Docker Compose
      command: |
        sudo curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
  intall-python-versions: &intall-python-versions
    run:
      name: Install required Python versions
      command: |
        cd ~/project
        for ver in $(cat .python-version); do
          pyenv install -sv $ver &
        done
        wait
  install-tox: &install-tox
    run:
      name: Install Tox
      command: sudo pip install tox
  fetch-dependencies-via-tox: &fetch-dependencies-via-tox
    run:
      name: Fetch dependencies via Tox
      command: tox -e phial --notest
  restore-cache-dependencies: &restore-cache-dependencies
    # Download and cache dependencies
    restore_cache:
      keys:
        - v2-dependencies-{{ checksum "tox.ini" }}
  save-cache-dependencies: &save-cache-dependencies
    save_cache:
      paths:
       - ./tox
      key: v2-dependencies-{{ checksum "tox.ini" }}
  restore-cache-pyenv: &restore-cache-pyenv
    restore_cache:
      keys:
        - v2-pyenv-{{ checksum ".python-version" }}
  save-cache-pyenv: &save-cache-pyenv
    save_cache:
      paths:
       - /opt/circleci/.pyenv/versions
      key: v2-pyenv-{{ checksum ".python-version" }}
  phial: &phial
    run:
      name: Run integration tests using Phial
      command: tox -e phial -- -m $GROUP

  steps: &steps
    steps:
      - checkout
      - *install-docker-compose
      - *restore-cache-pyenv
      - *intall-python-versions
      - *save-cache-pyenv
      - *install-tox
      - *restore-cache-dependencies
      - *fetch-dependencies-via-tox
      - *save-cache-dependencies
      - *phial


workflows:
  version: 2
  integration-tests:
    jobs:
      - centos-6
      - centos-7
      - oraclelinux-6
      - oraclelinux-7
      - debian-8
      - debian-9
      - ubuntu-1404
      - ubuntu-1604

jobs:
  centos-6:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: centos6
  centos-7:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: centos7
  oraclelinux-6:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: oraclelinux6
  oraclelinux-7:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: oraclelinux7
  ubuntu-1404:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: ubuntu1404
  ubuntu-1604:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: ubuntu1604
  debian-8:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: debian8
  debian-9:
    <<: *environment-defaults
    <<: *steps
    environment:
      GROUP: debian9
